using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{

    public static class Vin_info
    {
        static List<string> alf = new List<string>() { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "H", "J", "K", "L", "M", "N", "P", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0" };
        public static List<DigLet> digAlf = new List<DigLet>()
        {
            new DigLet('A',1),
            new DigLet('B',2),
            new DigLet('C',3),
            new DigLet('D',4),
            new DigLet('E',5),
            new DigLet('F',6),
            new DigLet('G',7),
            new DigLet('H',8),
            new DigLet('J',1),
            new DigLet('K',2),
            new DigLet('L',3),
            new DigLet('M',4),
            new DigLet('N',5),
            new DigLet('P',7),
            new DigLet('R',9),
            new DigLet('S',2),
            new DigLet('T',3),
            new DigLet('U',4),
            new DigLet('V',5),
            new DigLet('W',6),
            new DigLet('X',7),
            new DigLet('Y',8),
            new DigLet('Z',9),
            new DigLet('0',0),
            new DigLet('1',1),
            new DigLet('2',2),
            new DigLet('3',3),
            new DigLet('4',4),
            new DigLet('5',5),
            new DigLet('6',6),
            new DigLet('7',7),
            new DigLet('8',8),
            new DigLet('9',9),

        };
       public static List<Year> Yalf = new List<Year>()
        {
            new Year(1980,'A'),
            new Year(1981,'B'),
            new Year(1982,'C'),
            new Year(1983,'D'),
            new Year(1984,'E'),
            new Year(1985,'F'),
            new Year(1986,'G'),
            new Year(1987,'H'),
            new Year(1988,'J'),
            new Year(1989,'K'),
            new Year(1990,'L'),
            new Year(1991,'M'),
            new Year(1992,'N'),
            new Year(1993,'P'),
            new Year(1994,'R'),
            new Year(1995,'S'),
            new Year(1996,'T'),
            new Year(1997,'V'),
            new Year(1998,'W'),
            new Year(1999,'X'),
            new Year(2000,'Y'),
            new Year(2001,'1'),
            new Year(2002,'2'),
            new Year(2003,'3'),
            new Year(2004,'4'),
            new Year(2005,'5'),
            new Year(2006,'6'),
            new Year(2007,'7'),
            new Year(2008,'8'),
            new Year(2009,'9'),
            new Year(2010,'A'),
            new Year(2011,'B'),
            new Year(2012,'C'),
            new Year(2013,'D'),
            new Year(2014,'E'),
            new Year(2015,'F'),
            new Year(2016,'G'),
            new Year(2017,'H'),
            new Year(2018,'J'),
            new Year(2019,'K'),
            new Year(2020,'L'),
            new Year(2021,'M'),
            new Year(2022,'N'),
            new Year(2023,'P'),
            new Year(2024,'R'),
            new Year(2025,'S'),
            new Year(2026,'T'),
            new Year(2027,'V'),
            new Year(2028,'W'),
            new Year(2029,'X'),
            new Year(2030,'Y'),
            new Year(2031,'1'),
            new Year(2032,'2'),
            new Year(2033,'3'),
            new Year(2034,'4'),
            new Year(2035,'5'),
            new Year(2036,'6'),
            new Year(2037,'7'),
            new Year(2038,'8'),
            new Year(2039,'9'),
        };

        public static List<Continent> Continents = new List<Continent>() {
        new Continent("Африка", alf.GetRange(10, 8),
                new List<Country>()
                {
            new Country("ЮАР",alf[10], alf.GetRange(10, 8)),
            new Country("Котд’Ивуар", alf[10], alf.GetRange(18, 5)),
            new Country("не используется", alf[10], alf.GetRange(23, 11)),
            new Country("Ангола", alf[11], alf.GetRange(10, 5)),
            new Country("Кения", alf[11], alf.GetRange(15, 5)),
            new Country("Танзания", alf[11], alf.GetRange(20, 5)),
            new Country("не используется", alf[11], alf.GetRange(25, 9)),
            new Country("Бенин", alf[12], alf.GetRange(10, 5)),
            new Country("Мадагаскар", alf[12], alf.GetRange(15, 5)),
            new Country("Тунис", alf[12], alf.GetRange(20, 5)),
            new Country("не используется", alf[12], alf.GetRange(25, 9)),
            new Country("Египет", alf[13], alf.GetRange(10, 5)),
            new Country("Марокко", alf[13], alf.GetRange(15, 5)),
            new Country("Замбия", alf[13], alf.GetRange(20, 5)),
            new Country("не используется", alf[13], alf.GetRange(25, 9)),
            new Country("Эфиопия", alf[14], alf.GetRange(10, 5)),
            new Country("Мозамбик", alf[14], alf.GetRange(15, 5)),
            new Country("не используется", alf[14], alf.GetRange(20, 14)),
            new Country("Гана", alf[15], alf.GetRange(10, 5)),
            new Country("Нигерия", alf[15], alf.GetRange(15, 5)),
            new Country("не используется", alf[15], alf.GetRange(20, 14)),
            new Country("не используется", alf[16], alf.GetRange(0, 33)),
            new Country("не используется", alf[17], alf.GetRange(0, 33))
                }),

            new Continent("Азия", alf.GetRange(18, 7),
                new List<Country>()
                {
            new Country("Япония", alf[18], alf.GetRange(10, 17)),
            new Country("Шри Ланка", alf[19], alf.GetRange(10, 5)),
            new Country("Израиль", alf[19], alf.GetRange(15, 5)),
            new Country("Южная Корея", alf[19], alf.GetRange(20, 5)),
            new Country("Казахстан", alf[19], alf.GetRange(25, 9)),
            new Country("Китай", alf[20], alf.GetRange(10, 24)),
            new Country("Индия", alf[21], alf.GetRange(10, 5)),
            new Country("Индонезия", alf[21], alf.GetRange(15, 5)),
            new Country("Таиланд", alf[21], alf.GetRange(20, 5)),
            new Country("не используется", alf[21], alf.GetRange(25, 9)),
            new Country("Пакистан", alf[22], alf.GetRange(15, 5)),
            new Country("Турция", alf[22], alf.GetRange(20, 5)),
            new Country("не используется", alf[22], alf.GetRange(25, 9)),
            new Country("Филиппины", alf[23], alf.GetRange(10, 5)),
            new Country("Сингапур", alf[23], alf.GetRange(15, 5)),
            new Country("Малайзия", alf[23], alf.GetRange(20, 5)),
            new Country("не используется", alf[23], alf.GetRange(25, 9)),
            new Country("ОАЭ", alf[24], alf.GetRange(10, 5)),
            new Country("Тайвань", alf[24], alf.GetRange(15, 5)),
            new Country("Вьетнам", alf[24], alf.GetRange(20, 5)),
            new Country("Саудовская Аравия", alf[24], alf.GetRange(25, 9)),
            }),


            new Continent("Европа", alf.GetRange(25, 8),
                new List<Country>()
                {
            new Country("Великобритания", alf[25], alf.GetRange(10, 12)),
            new Country("Германия", alf[25], alf.GetRange(22, 5)),
            new Country("Польша", alf[25], alf.GetRange(27, 6)),
            new Country("Латвия", alf[25], alf.GetRange(1, 5)),
            new Country("Швейцария", alf[26], alf.GetRange(10, 8)),
            new Country("Чехия", alf[26], alf.GetRange(18, 6)),
            new Country("Венгрия", alf[26], alf.GetRange(24, 5)),
            new Country("Португалия", alf[26], alf.GetRange(29, 6)),
            new Country("не используется", alf[26], alf.GetRange(2, 7)),
            new Country("не используется", alf[27], alf.GetRange(10, 7)),
            new Country("Дания", alf[27], alf.GetRange(17, 5)),
            new Country("Ирландия", alf[27], alf.GetRange(22, 5)),
            new Country("Румыния", alf[27], alf.GetRange(27, 6)),
            new Country("не используется", alf[27], alf.GetRange(1, 4)),
            new Country("Словакия", alf[27], alf.GetRange(5, 3)),
            new Country("не используется", alf[27], alf.GetRange(8, 2)),
            new Country("Австрия", alf[28], alf.GetRange(10, 5)),
            new Country("Франция", alf[28], alf.GetRange(15, 10)),
            new Country("Испания", alf[28], alf.GetRange(25, 5)),
            new Country("Сербия", alf[28], alf.GetRange(30, 6)),
            new Country("Хорватия", alf[28], alf.GetRange(3, 3)),
            new Country("Эстония", alf[28], alf.GetRange(6, 5)),
            new Country("Германия", alf[29], alf.GetRange(0, 33)),
            new Country("Болгария", alf[30], alf.GetRange(10, 5)),
            new Country("Греция", alf[30], alf.GetRange(15, 5)),
            new Country("Нидерланды", alf[30], alf.GetRange(20, 5)),
            new Country("СССР/СНГ", alf[30], alf.GetRange(25, 5)),
            new Country("Люксембург", alf[30], alf.GetRange(30, 6)),
            new Country("Россия", alf[30], alf.GetRange(36, 8)),
            new Country("Бельгия", alf[31], alf.GetRange(10, 5)),
            new Country("Финляндия", alf[31], alf.GetRange(15, 5)),
            new Country("Мальта", alf[31], alf.GetRange(20, 5)),
            new Country("Швеция", alf[31], alf.GetRange(25, 5)),
            new Country("Норвегия", alf[31], alf.GetRange(30, 6)),
            new Country("Беларусь", alf[31], alf.GetRange(36, 3)),
            new Country("Украина", alf[31], alf.GetRange(39, 5)),
            new Country("Италия", alf[32], alf.GetRange(10, 15)),
            new Country("не используется", alf[32], alf.GetRange(25, 5)),
            new Country("Словения", alf[32], alf.GetRange(30, 6)),
            new Country("Литва", alf[32], alf.GetRange(36, 3)),
            new Country("Россия", alf[32], alf.GetRange(39, 5)),
            }),

            new Continent("Северная Америка", alf.GetRange(1, 5),
                new List<Country>()
                {
            new Country("США", alf[1], alf.GetRange(0, 33)),
            new Country("Канада", alf[2], alf.GetRange(0, 33)),
            new Country("Мексика", alf[3], alf.GetRange(10, 20)),
            new Country("Коста Рика", alf[3], alf.GetRange(30, 11)),
            new Country("Каймановы острова", alf[3], alf.GetRange(41, 3)),
            new Country("США", alf[4], alf.GetRange(0, 33)),
            new Country("США", alf[5], alf.GetRange(0, 33)),

            }),

            new Continent("Океания", alf.GetRange(6, 2),
    new List<Country>()
    {
            new Country("Австралия", alf[6], alf.GetRange(10, 20)),
            new Country("не используется", alf[6], alf.GetRange(39, 5)),
            new Country("Новая Зеландия", alf[7], alf.GetRange(10, 5)),
            new Country("не используется", alf[7], alf.GetRange(15, 29)),
}
    ),
            new Continent("Южная Америка", alf.GetRange(8, 2),
    new List<Country>()
    {
            new Country("Аргентина", alf[8], alf.GetRange(10, 5)),
            new Country("Чили", alf[8], alf.GetRange(15, 5)),
            new Country("Эквадор", alf[8], alf.GetRange(20, 5)),
            new Country("Перу", alf[8], alf.GetRange(25, 5)),
            new Country("Венесуэла", alf[8], alf.GetRange(30, 6)),
            new Country("не используется", alf[8], alf.GetRange(36, 8)),
            new Country("Бразилия", alf[9], alf.GetRange(10, 5)),
            new Country("Колумбия", alf[9], alf.GetRange(15, 5)),
            new Country("Парагвай", alf[9], alf.GetRange(20, 5)),
            new Country("Уругвай", alf[9], alf.GetRange(25, 5)),
            new Country("Тринидад и Тобаго", alf[9], alf.GetRange(30, 6)),
            new Country("Бразилия", alf[9], alf.GetRange(36, 5)),
            new Country("не используется", alf[9], alf.GetRange(0, 1)),
}
    ),
            };
        
    }
}
